# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Programování a vývoj aplikací
author: Josef Malý
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  

sphinx:
  config:
    html_theme: furo

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/Smichovska-SPS/notes/  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  announcement: "<p'>⚠️ Tyto skripta jsou v raném vývoji ⚠️</p>"
  comments:
    utterances:
      repo: "Smichovska-SPS/notes"
      theme: "github-dark"
  source_repository: "https://github.com/Smichovska-SPS/notes",
  source_branch: "main",
  source_directory: "/",


exclude_patterns: [./test.ipynb, ./README.md]
